### PR TITLE
preserve cert-manager added labels

### PR DESCRIPTION
**Pull request by Tirumalavasa**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44461

### CODE REVIEW

**Comment by Tirumalavasa** [comment]
@ShinojEdakkara^^

**Review by dongwangdw — COMMENTED** [review]
Please rebase the commits into one.
The lint-go errors comes from your original fix commits.

As I see from the issue, the node exporter did restart. But you added the labels. Have you ever checked it?

**Comment by Tirumalavasa** [comment]
> Please rebase the commits into one.
> The lint-go errors comes from your original fix commits.
> 
> As I see from the issue, the node exporter did restart. But you added the labels. Have you ever checked it?

@dongwangdw I have rebased the commits, Today i checked the all the pods which are restarted when cert secret is removed, But i didn't see any pod preserving `certmanager.k8s.io/time-restarted` label even after the pods get restarted.

**Comment by Tirumalavasa** [comment]
@swati-nair, Can you also take a look at this PR once, I am not able to find you on reviewers search to assign you as reviewer

**Comment by swati-nair** [comment]
@Tirumalavasa The changes look good, but as I see from the above comments, the pods don't have the label after restart. Is it now resolved?

**Comment by Tirumalavasa** [comment]
> @Tirumalavasa The changes look good, but as I see from the above comments, the pods don't have the label after restart. Is it now resolved?

@swati-nair , The above test performed doesn't have this code changes, i will need to test with operator image which has this PR changes present.

**Comment by Tirumalavasa** [comment]
> > @Tirumalavasa The changes look good, but as I see from the above comments, the pods don't have the label after restart. Is it now resolved?
> 
> @swati-nair , The above test performed doesn't have this code changes, i will need to test with operator image which has this PR changes present.

I have tested it, cert-manager label is getting preserved

**Pull request merged**
